# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-yyMR5A-pvmDav_vjuOUYTDrwh1QtgM
"""

import gradio as gr
import numpy as np
import tensorflow as tf
from PIL import Image

# Load your trained model (you'll need to save it first from your notebook)
# Add this to the end of your notebook: model.save('malaria_model.h5')
model = tf.keras.models.load_model('malaria_model.h5')

def preprocess_image(image):
    """Preprocess image to match training format"""
    # Resize to 150x150
    image = image.resize((150, 150))
    # Convert to array and normalize
    img_array = np.array(image) / 255.0
    # Add batch dimension
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

def predict(image):
    """Make prediction on uploaded image"""
    if image is None:
        return "Please upload an image"

    # Preprocess
    processed_img = preprocess_image(image)

    # Predict
    prediction = model.predict(processed_img, verbose=0)[0][0]

    # Interpret results
    if prediction > 0.5:
        result = "🦠 **PARASITIZED** (Malaria Detected)"
        confidence = prediction * 100
    else:
        result = "✅ **UNINFECTED** (No Malaria)"
        confidence = (1 - prediction) * 100

    return f"{result}\n\nConfidence: {confidence:.2f}%"

# Create Gradio interface
interface = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil", label="Upload Blood Cell Image"),
    outputs=gr.Textbox(label="Diagnosis Result"),
    title="🔬 Malaria Detection System",
    description="Upload a microscopic blood cell image to detect malaria infection using AI",
    examples=None,
    theme="soft"
)

if __name__ == "__main__":
    interface.launch()