# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-yyMR5A-pvmDav_vjuOUYTDrwh1QtgM
"""

import gradio as gr
import numpy as np
import tensorflow as tf
from PIL import Image

# ✅ Load your model (make sure filename matches exactly)
model = tf.keras.models.load_model('model.h5', compile=False)

def preprocess_image(image):
    """Preprocess image to match training format"""
    image = image.resize((150, 150))
    img_array = np.array(image) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

def predict(image):
    """Make prediction on uploaded image"""
    if image is None:
        return "Please upload an image"

    processed_img = preprocess_image(image)
    prediction = model.predict(processed_img, verbose=0)[0][0]

    if prediction > 0.5:
        result = "🦠 **PARASITIZED** (Malaria Detected)"
        confidence = prediction * 100
    else:
        result = "✅ **UNINFECTED** (No Malaria)"
        confidence = (1 - prediction) * 100

    return f"{result}\n\nConfidence: {confidence:.2f}%"

# ✅ Create Gradio interface
interface = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil", label="Upload Blood Cell Image"),
    outputs=gr.Textbox(label="Diagnosis Result"),
    title="🔬 Malaria Detection System",
    description="Upload a microscopic blood cell image to detect malaria infection using AI",
    theme="soft"
)

# ✅ Launch interface
if __name__ == "__main__":
    interface.launch()